# Generated by Django 6.0.3 on 2026-03-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('occasion', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('RNB', 'R&B')], max_length=20)),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ENERGETIC', 'Energetic'), ('RELAXED', 'Relaxed')], max_length=20)),
                ('voice_type', models.CharField(max_length=100)),
                ('lyrics', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='GENERATING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song.prompt')),
            ],
        ),
    ]
