# Generated by Django 6.0.3 on 2026-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
