# Generated by Django 6.0.3 on 2026-03-21 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongListener',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='song_listener', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Song Listener',
                'verbose_name_plural': 'Song Listeners',
            },
        ),
        migrations.CreateModel(
            name='SongCreator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='song_creator', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ManyToManyField(blank=True, help_text='Song library (max 20 songs)', related_name='creators', to='song.song')),
            ],
            options={
                'verbose_name': 'Song Creator',
                'verbose_name_plural': 'Song Creators',
            },
        ),
    ]
